In [ ]:
def f(x):
    return x**2

sqaure = [f(i) for i in range (1,10)]
print(sqaure)

In [ ]:
str = ['hello',24,0.156,'false']
str[3]
str[2] = 0.146
print(str)

In [ ]:
inp_dict = {'a': 23, 'b': 40, 'c':34}
out_dict = []
for i in inp_dict:
    if inp_dict[i] > 25:
        out_dict.append(inp_dict[i])
print(out_dict)
        

In [ ]:
import random
random_val = random.randint(1,50)
print(random_val)

In [ ]:
marks_dict = {'math': 45, 'science': 89, 'physics': 90}
output_list = []
z = list(marks_dict.values())
if z[0] >= 75:
    output_list.append(z[0])
if z[1] >= 75:
    output_list.append(z[1])
if z[2] >= 75:
    output_list.append(z[2])
    
output_list

In [ ]:
sum =0
for i in range(0,100):
    sum *= i
print(sum)
    

In [ ]:

even_list = [i**2  for i in range(1,10) if i %2 ==0  ]
even_list

In [ ]:
for x in range(4,6):
    for y in range(1,11):
        print('{} * {} = {}'.format(x,y,x*y))


In [ ]:
i = 0
while i <=5:
    print(i)
    i = i +1

In [ ]:
statement = 'my name is shreedhar and I am 22 years old'
number = [i  for i in statement if i.isdigit()]
print(number)

In [ ]:
names = ['sam', 'kate','aj', 'moen','john']
i = 0
while i < len(names):
    name = names[i]
    i += 1
    
    if name == 'kate':
        continue
    
    print(name)

In [ ]:
some_list = []

for i in range(10):
  some_list.append(f(i))
print(some_list)

Numpy practices

In [3]:
import numpy as np
matrix = np.arange(1,10)
arr_to_matrix = matrix.reshape(3,3)
print(arr_to_matrix)
print(np.min(arr_to_matrix))
print(np.max(arr_to_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9


In [5]:
random_mat = np.random.randn(5,5)
random_mat
print('mean', np.mean(random_mat))
print('std', np.std(random_mat))

mean -0.1895114272492109
std 0.98493171461813


In [7]:
random_int = np.random.randint(1,5,[5,5])
random_int

array([[4, 2, 1, 1, 2],
       [2, 1, 4, 1, 4],
       [4, 1, 3, 1, 1],
       [1, 3, 1, 3, 1],
       [4, 2, 2, 1, 2]])

In [9]:
mat1 = np.arange(-9,0,1).reshape(3,3)
print(np.min(mat1))
print(np.max(mat1))

-9
-1


In [13]:
rand_arr = np.random.rand(10)
print(rand_arr[rand_arr>0.5])

[0.5546279  0.56095358 0.55005915 0.94485227]


In [15]:
rand_norm_dist = np.random.randn(5,5)
rand_norm_dist

array([[ 0.23846314,  1.75056161, -0.95317073,  0.94067433, -0.49998634],
       [-0.14804783, -1.21337863,  1.23425477,  0.93522297,  1.1498059 ],
       [-0.76348313,  0.5372772 ,  0.47579413,  0.21228912,  0.43507744],
       [ 0.03250608, -0.40612034, -0.25604249, -0.04269301,  0.3599114 ],
       [ 1.53905631, -0.15369529, -0.23695191, -0.61421697,  0.51554935]])

In [17]:
rand_norm_dist[1]

array([-0.14804783, -1.21337863,  1.23425477,  0.93522297,  1.1498059 ])

In [19]:
rand_norm_dist[1,2]

1.2342547679639564

In [21]:
rand_norm_dist[0:2, 1:3]

array([[ 1.75056161, -0.95317073],
       [-1.21337863,  1.23425477]])

In [23]:
rand_norm_dist[1,1] = 2

In [25]:
rand_norm_dist

array([[ 0.23846314,  1.75056161, -0.95317073,  0.94067433, -0.49998634],
       [-0.14804783,  2.        ,  1.23425477,  0.93522297,  1.1498059 ],
       [-0.76348313,  0.5372772 ,  0.47579413,  0.21228912,  0.43507744],
       [ 0.03250608, -0.40612034, -0.25604249, -0.04269301,  0.3599114 ],
       [ 1.53905631, -0.15369529, -0.23695191, -0.61421697,  0.51554935]])

In [29]:
rand_norm_dist[1:4,1:4] = 2

In [31]:
rand_norm_dist

array([[ 0.23846314,  1.75056161, -0.95317073,  0.94067433, -0.49998634],
       [-0.14804783,  2.        ,  2.        ,  2.        ,  1.1498059 ],
       [-0.76348313,  2.        ,  2.        ,  2.        ,  0.43507744],
       [ 0.03250608,  2.        ,  2.        ,  2.        ,  0.3599114 ],
       [ 1.53905631, -0.15369529, -0.23695191, -0.61421697,  0.51554935]])

In [33]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [35]:
rand_norm_dist

array([[ 0.23846314,  1.75056161, -0.95317073,  0.94067433, -0.49998634],
       [-0.14804783,  2.        ,  2.        ,  2.        ,  1.1498059 ],
       [-0.76348313,  2.        ,  2.        ,  2.        ,  0.43507744],
       [ 0.03250608,  2.        ,  2.        ,  2.        ,  0.3599114 ],
       [ 1.53905631, -0.15369529, -0.23695191, -0.61421697,  0.51554935]])

In [39]:
new_mat = rand_norm_dist[0:3,0:3]
new_mat

array([[ 0.23846314,  1.75056161, -0.95317073],
       [-0.14804783,  2.        ,  2.        ],
       [-0.76348313,  2.        ,  2.        ]])

In [41]:
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [47]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array1.copy()
array2[1,1] = 124
print(array2)
print(array1)

[[  1   2   3]
 [  4 124   6]
 [  7   8   9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
np.savez('/Users/ravs/Desktop/UTA-AIML/random_matrix',rand_norm_dist=rand_norm_dist,new_mat=new_mat)

In [77]:
load_multi = np.load('/Users/ravs/Desktop/UTA-AIML/random_matrix.npz')

In [69]:
load_multi['rand_norm_dist']

array([[ 0.23846314,  1.75056161, -0.95317073,  0.94067433, -0.49998634],
       [-0.14804783,  2.        ,  2.        ,  2.        ,  1.1498059 ],
       [-0.76348313,  2.        ,  2.        ,  2.        ,  0.43507744],
       [ 0.03250608,  2.        ,  2.        ,  2.        ,  0.3599114 ],
       [ 1.53905631, -0.15369529, -0.23695191, -0.61421697,  0.51554935]])

In [73]:
np.savetxt('/Users/ravs/Desktop/UTA-AIML/random_matrix.txt',rand_norm_dist,delimiter=',')

In [ ]:
import pandas as pd